import { Promotion, PromoCarouselItem } from '@/types';

function getTodayAt(hour: number, minute: number = 0): string {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

function getTodayEnd(): string {
  const date = new Date();
  date.setHours(23, 59, 59, 999);
  return date.toISOString();
}

export const PROMO_CAROUSEL_ITEMS: PromoCarouselItem[] = [
  { id: 'date-night', label: 'Date Night', color: '#DC2626' },
  { id: 'happy-hour', label: 'Happy Hour', color: '#EA580C' },
  { id: 'new-openings', label: 'New Openings', color: '#059669' },
  { id: 'student-deals', label: 'Student Deals', color: '#2563EB' },
];

export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: 'promo_001',
    merchantId: 'merchant_001',
    merchantName: 'Atlas Bar & Kitchen',
    merchantLogo: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=200',
    title: 'Free House Drink',
    description: 'Get a complimentary house cocktail with any dinner entrée',
    perkType: 'drink',
    perkValue: 12,
    minSpend: 25,
    startTime: getTodayAt(17),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startHour: 17,
    endHour: 21,
    radiusMeters: 40000,
    budgetCents: 100000,
    dailyCap: 50,
    active: true,
    tags: ['Date Night', 'Happy Hour'],
    geo: { lat: 41.6397, lng: -81.4067 },
    address: '4057 Erie St, Willoughby, OH 44094',
    category: 'bar',
    fineprint: '21+, dine-in only, 1 per person',
    sponsored: true,
  },
  {
    id: 'promo_002',
    merchantId: 'merchant_002',
    merchantName: '1899 Pub',
    merchantLogo: 'https://images.unsplash.com/photo-1572116469696-31de0f17cc34?w=200',
    title: 'Free Appetizer',
    description: 'Complimentary wings or fries with 1Way arrival',
    perkType: 'appetizer',
    perkValue: 10,
    minSpend: 20,
    startTime: getTodayAt(17),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startHour: 17,
    endHour: 22,
    radiusMeters: 40000,
    budgetCents: 150000,
    dailyCap: 75,
    active: true,
    tags: ['Happy Hour', 'Sports'],
    geo: { lat: 41.6392, lng: -81.4073 },
    address: '4085 Erie St, Willoughby, OH 44094',
    category: 'bar',
    fineprint: 'Dine-in only, not valid with other offers',
    sponsored: true,
  },
  {
    id: 'promo_003',
    merchantId: 'merchant_003',
    merchantName: 'The Marble Room',
    merchantLogo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200',
    title: '$15 Off Your Bill',
    description: 'Save $15 on dinner when you arrive via 1Way',
    perkType: 'dollar_off',
    perkValue: 15,
    minSpend: 50,
    startTime: getTodayAt(18),
    endTime: getTodayEnd(),
    daysOfWeek: [5, 6],
    startHour: 18,
    endHour: 23,
    radiusMeters: 50000,
    budgetCents: 200000,
    dailyCap: 40,
    active: true,
    tags: ['Date Night', 'Fine Dining'],
    geo: { lat: 41.4989, lng: -81.6921 },
    address: '623 Euclid Ave, Cleveland, OH 44114',
    category: 'bar',
    fineprint: 'Valid Fri-Sat only, reservations recommended',
    sponsored: false,
  },
  {
    id: 'promo_004',
    merchantId: 'merchant_004',
    merchantName: 'Ballantine',
    merchantLogo: 'https://images.unsplash.com/photo-1544148103-0773bf10d330?w=200',
    title: '50% Off Apps',
    description: 'Half price appetizers 5-7 PM daily',
    perkType: 'percent_off',
    perkValue: 50,
    minSpend: 15,
    startTime: getTodayAt(17),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startHour: 17,
    endHour: 19,
    radiusMeters: 40000,
    budgetCents: 80000,
    dailyCap: 60,
    active: true,
    tags: ['Happy Hour'],
    geo: { lat: 41.6395, lng: -81.4069 },
    address: '4063 Erie St, Willoughby, OH 44094',
    category: 'bar',
    fineprint: 'Valid 5-7 PM only, dine-in',
    sponsored: false,
  },
  {
    id: 'promo_005',
    merchantId: 'merchant_005',
    merchantName: 'Willoughby Brewing Co.',
    merchantLogo: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=200',
    title: 'Free Pint with Purchase',
    description: 'Free craft beer with any entrée order',
    perkType: 'drink',
    perkValue: 8,
    minSpend: 18,
    startTime: getTodayAt(17),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4],
    startHour: 17,
    endHour: 21,
    radiusMeters: 40000,
    budgetCents: 120000,
    dailyCap: 80,
    active: true,
    tags: ['Happy Hour', 'Craft Beer'],
    geo: { lat: 41.6399, lng: -81.4065 },
    address: '4057 Erie St, Willoughby, OH 44094',
    category: 'bar',
    fineprint: '21+, Mon-Fri only, dine-in',
    sponsored: true,
  },
  {
    id: 'promo_006',
    merchantId: 'merchant_006',
    merchantName: 'The Morehouse',
    merchantLogo: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?w=200',
    title: '$5 Off Ride Home',
    description: 'Get $5 off your return ride when you dine with us',
    perkType: 'dollar_off',
    perkValue: 5,
    minSpend: 30,
    startTime: getTodayAt(17),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startHour: 17,
    endHour: 23,
    radiusMeters: 40000,
    budgetCents: 100000,
    dailyCap: 50,
    active: true,
    tags: ['Date Night', 'Return Ride'],
    geo: { lat: 41.6393, lng: -81.4071 },
    address: '4077 Erie St, Willoughby, OH 44094',
    category: 'bar',
    fineprint: 'Applied to return ride only',
    sponsored: false,
  },
  {
    id: 'promo_007',
    merchantId: 'merchant_007',
    merchantName: 'Barrio Tacos',
    merchantLogo: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=200',
    title: 'Free Guac & Chips',
    description: 'Complimentary guacamole and chips for 1Way riders',
    perkType: 'appetizer',
    perkValue: 9,
    minSpend: 20,
    startTime: getTodayAt(11),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startHour: 11,
    endHour: 22,
    radiusMeters: 50000,
    budgetCents: 150000,
    dailyCap: 100,
    active: true,
    tags: ['Happy Hour', 'New Openings'],
    geo: { lat: 41.5043, lng: -81.6163 },
    address: '806 Literary Rd, Cleveland, OH 44113',
    category: 'bar',
    fineprint: 'Dine-in only, 1 per table',
    sponsored: true,
  },
  {
    id: 'promo_008',
    merchantId: 'merchant_008',
    merchantName: 'Novo Coffee',
    merchantLogo: 'https://images.unsplash.com/photo-1559305616-3fea02a5e551?w=200',
    title: 'Student Discount 20%',
    description: '20% off with valid student ID',
    perkType: 'percent_off',
    perkValue: 20,
    minSpend: 10,
    startTime: getTodayAt(7),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startHour: 7,
    endHour: 20,
    radiusMeters: 60000,
    budgetCents: 50000,
    dailyCap: 200,
    active: true,
    tags: ['Student Deals', 'Coffee'],
    geo: { lat: 41.5014, lng: -81.6789 },
    address: '1700 E 12th St, Cleveland, OH 44114',
    category: 'bar',
    fineprint: 'Valid student ID required',
    sponsored: false,
  },
  {
    id: 'promo_009',
    merchantId: 'merchant_009',
    merchantName: 'Melt Bar & Grilled',
    merchantLogo: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=200',
    title: 'Free Side with Sandwich',
    description: 'Free fries or slaw with any sandwich purchase',
    perkType: 'appetizer',
    perkValue: 7,
    minSpend: 15,
    startTime: getTodayAt(11),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startHour: 11,
    endHour: 23,
    radiusMeters: 50000,
    budgetCents: 180000,
    dailyCap: 150,
    active: true,
    tags: ['Lunch', 'Dinner'],
    geo: { lat: 41.4846, lng: -81.7178 },
    address: '14718 Detroit Ave, Lakewood, OH 44107',
    category: 'bar',
    fineprint: 'Valid all day, dine-in or takeout',
    sponsored: false,
  },
  {
    id: 'promo_010',
    merchantId: 'merchant_010',
    merchantName: 'Terrestrial Brewing',
    merchantLogo: 'https://images.unsplash.com/photo-1532634922-8fe0b757fb13?w=200',
    title: 'Buy 1 Get 1 Beer',
    description: 'BOGO on all draft beers 4-6 PM',
    perkType: 'free_item',
    perkValue: 7,
    minSpend: 7,
    startTime: getTodayAt(16),
    endTime: getTodayEnd(),
    daysOfWeek: [0, 1, 2, 3, 4, 5, 6],
    startHour: 16,
    endHour: 18,
    radiusMeters: 50000,
    budgetCents: 100000,
    dailyCap: 80,
    active: true,
    tags: ['Happy Hour', 'Craft Beer'],
    geo: { lat: 41.5042, lng: -81.6165 },
    address: '7524 Father Frascati Dr, Cleveland, OH 44102',
    category: 'bar',
    fineprint: '21+, 4-6 PM only, equal or lesser value',
    sponsored: true,
  },
];
